export const images = {
  sceneBackdrop: require('../assets/concierge_guest_scene_backdrop.png'),
  splashScene: require('../assets/concierge_guest_splash_scene.png'),
  loaderLogo: require('../assets/concierge_guest_loader_logo.png'),
  guestMark: require('../assets/concierge_guest_guest_mark.png'),
  appMark: require('../assets/concierge_guest_app_mark.png'),
  welcomeBackdrop1: require('../assets/concierge_guest_welcome_backdrop_1.png'),
  welcomeBackdrop2: require('../assets/concierge_guest_welcome_backdrop_2.png'),
  welcomeBackdrop3: require('../assets/concierge_guest_welcome_backdrop_3.png'),
  welcomeIllustration1: require('../assets/concierge_guest_welcome_illustration_1.png'),
  welcomeIllustration2: require('../assets/concierge_guest_welcome_illustration_2.png'),
  welcomeIllustration3: require('../assets/concierge_guest_welcome_illustration_3.png'),
  dishes: {
    classicBreakfast: require('../assets/concierge_guest_dish_classic_breakfast.png'),
    appetizerBoard: require('../assets/concierge_guest_dish_appetizer_board.png'),
    celticComfort: require('../assets/concierge_guest_dish_celtic_comfort.png'),
    celticShareBites: require('../assets/concierge_guest_dish_celtic_share_bites.png'),
    chocolateCake: require('../assets/concierge_guest_dish_chocolate_cake.png'),
    citrusMocktail: require('../assets/concierge_guest_dish_citrus_mocktail.png'),
    coastalIcedTea: require('../assets/concierge_guest_dish_coastal_iced_tea.png'),
    coastalSalad: require('../assets/concierge_guest_dish_coastal_salad.png'),
    dessertTrio: require('../assets/concierge_guest_dish_dessert_trio.png'),
    fishAndChips: require('../assets/concierge_guest_dish_fish_and_chips.png'),
    fridayFeast: require('../assets/concierge_guest_dish_friday_feast.png'),
    fruitCreamCup: require('../assets/concierge_guest_dish_fruit_cream_cup.png'),
    gardenNoodlePlate: require('../assets/concierge_guest_dish_garden_noodle_plate.png'),
    gardenSignatureBowl: require('../assets/concierge_guest_dish_garden_signature_bowl.png'),
    grillBurger: require('../assets/concierge_guest_dish_grill_burger.png'),
    harbourChicken: require('../assets/concierge_guest_dish_harbour_chicken.png'),
    loungeLemonade: require('../assets/concierge_guest_dish_lounge_lemonade.png'),
    morningCoffee: require('../assets/concierge_guest_dish_morning_coffee.png'),
    saturdayFeast: require('../assets/concierge_guest_dish_saturday_feast.png'),
    weekendPlate: require('../assets/concierge_guest_dish_weekend_plate.png'),
  },
};
